BEGIN;

-- Pour aider les Windows Users ;-) 
SET client_encoding TO 'UTF8';

-- Supprimer les tables avant de les re-créer
DROP TABLE IF EXISTS
"user",
"recipe",
"ingredient",
"dish_category",
"difficulty",
"motion",
"motion_genre",
"motion_format",
"recipe_has_ingredient",
"motion_genre_has_motion";

-- -----------------------------------------------------
-- Table "user"
-- -----------------------------------------------------
CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "pseudo" VARCHAR(100) NOT NULL,
  password VARCHAR(128) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'member',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "ingredient"
-- -----------------------------------------------------
CREATE TABLE "ingredient" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(50) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "dish_category"
-- -----------------------------------------------------
CREATE TABLE "dish_category" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(50) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "difficulty"
-- -----------------------------------------------------
CREATE TABLE "difficulty" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(50) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "motion_format"
-- -----------------------------------------------------
CREATE TABLE "motion_format" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(50) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "motion"
-- -----------------------------------------------------
CREATE TABLE "motion" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR(150) NOT NULL,
  "picture" TEXT NOT NULL,
  "release_date" VARCHAR(20) NOT NULL,
  "director" VARCHAR(50) NOT NULL,
  "catchphrase" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "motion_format_id" INTEGER NOT NULL REFERENCES "motion_format"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "recipe"
-- -----------------------------------------------------
CREATE TABLE "recipe" (
"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"title" VARCHAR(150) NOT NULL,
"picture" TEXT NOT NULL,
"description" TEXT,
"instruction" TEXT NOT NULL,
"anecdote" TEXT,
"completion_time" INTEGER NOT NULL,
  "user_id" INTEGER REFERENCES "user"("id") ON DELETE SET NULL,
"dish_category_id" INTEGER NOT NULL REFERENCES "dish_category"("id"),
  "motion_id" INTEGER NOT NULL REFERENCES "motion"("id") ON DELETE CASCADE, 
"difficulty_id" INTEGER NOT NULL REFERENCES "difficulty"("id"),
"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "motion_genre"
-- -----------------------------------------------------
CREATE TABLE "motion_genre" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(50) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- Table "recipe_has_ingredient"
-- -----------------------------------------------------
CREATE TABLE "recipe_has_ingredient" (
  "ingredient_id" INTEGER NOT NULL REFERENCES "ingredient"("id"),
  "recipe_id" INTEGER NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE, 
  "quantity" INTEGER NOT NULL ,
  "unit" VARCHAR(20),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ,
  PRIMARY KEY ("ingredient_id", "recipe_id")
);/*clé primaire composite*/

-- -----------------------------------------------------
-- Table "motion_genre_has_motion"
-- -----------------------------------------------------
CREATE TABLE "motion_genre_has_motion" (
  "motion_genre_id" INTEGER NOT NULL REFERENCES "motion_genre"("id"),
  "motion_id" INTEGER NOT NULL REFERENCES "motion"("id") ON DELETE CASCADE, 
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ,
  PRIMARY KEY ("motion_genre_id", "motion_id")
);/*clé primaire composite*/

/* Fin de transaction en cas d'erreur ROLLBACK et toutes les actions seront annulées*/
COMMIT;
